/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.Usuarios.vista;

import com.unicauca.parqueadero.negocio.Bahia;
import com.unicauca.parqueadero.negocio.Conductor;
import com.unicauca.parqueadero.negocio.GestorConductores;
import com.unicauca.parqueadero.negocio.Vehiculo;
import com.unicauca.parqueadero.utilidades.Utilidades;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author w
 */
public class GUIInformacionUsuario extends javax.swing.JFrame {
    
    private GestorConductores gestor;
    private Conductor cond;
    private ArrayList<Vehiculo> vehiculos;
    private ArrayList<Bahia> bahias;
    /**
     * Creates new form GUILiberarCupo
     */
    public GUIInformacionUsuario() {
        initComponents();
        setVisible(true);
        gestor = new GestorConductores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNorte = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtNumeroDocumento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        jPanelSur = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTipoUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMultas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxNumeroPlaca2 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxBahias = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        btnAsignarCupo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxNumeroPlaca = new javax.swing.JComboBox();
        btnMostrarInfoVehiculo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtNumeroPlaca = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 554));
        getContentPane().setLayout(new java.awt.BorderLayout(3, 0));

        jPanelNorte.setBackground(new java.awt.Color(232, 239, 249));
        jPanelNorte.setAlignmentX(20.0F);
        jPanelNorte.setAlignmentY(20.0F);
        jPanelNorte.setLayout(new java.awt.GridLayout(3, 2));

        jLabel2.setText("Tipo de Documento");
        jPanelNorte.add(jLabel2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Carnet Universitario", "Cedula" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanelNorte.add(jComboBox1);

        jLabel8.setText("Numero Documento:");
        jPanelNorte.add(jLabel8);
        jPanelNorte.add(txtNumeroDocumento);
        jPanelNorte.add(jLabel1);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanelNorte.add(btnConsultar);

        getContentPane().add(jPanelNorte, java.awt.BorderLayout.PAGE_START);

        jPanelSur.setBackground(new java.awt.Color(232, 239, 249));
        jPanelSur.setPreferredSize(new java.awt.Dimension(400, 40));

        btnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanelSur.add(btnCerrar);

        getContentPane().add(jPanelSur, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        jLabel3.setText("Nombres:");
        jPanel1.add(jLabel3);
        jPanel1.add(txtNombres);

        jLabel4.setText("Apellidos:");
        jPanel1.add(jLabel4);
        jPanel1.add(txtApellidos);

        jLabel5.setText("Tipo Usuario:");
        jPanel1.add(jLabel5);
        jPanel1.add(txtTipoUsuario);

        jLabel6.setText("Numero Documento:");
        jPanel1.add(jLabel6);
        jPanel1.add(txtDocumento);

        jLabel7.setText("Multas:");
        jPanel1.add(jLabel7);
        jPanel1.add(txtMultas);

        jTabbedPane1.addTab("Informacion Usuario", jPanel1);

        jPanel3.setLayout(new java.awt.GridLayout(3, 2));

        jLabel12.setText("Vehiculo:");
        jPanel3.add(jLabel12);

        jComboBoxNumeroPlaca2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar Placa" }));
        jComboBoxNumeroPlaca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNumeroPlaca2ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxNumeroPlaca2);

        jLabel13.setText("Numero de bahia:");
        jPanel3.add(jLabel13);

        jComboBoxBahias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar Bahia" }));
        jPanel3.add(jComboBoxBahias);
        jPanel3.add(jLabel14);

        btnAsignarCupo.setText("Asiganar Cupo");
        btnAsignarCupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarCupoActionPerformed(evt);
            }
        });
        jPanel3.add(btnAsignarCupo);

        jTabbedPane1.addTab("Asiganar Cupo", jPanel3);

        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        jComboBoxNumeroPlaca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Numero de placa" }));
        jComboBoxNumeroPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNumeroPlacaActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxNumeroPlaca);

        btnMostrarInfoVehiculo.setText("Mostrar Informacion");
        btnMostrarInfoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarInfoVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(btnMostrarInfoVehiculo);

        jLabel9.setText(" Numero de placa:");
        jPanel2.add(jLabel9);
        jPanel2.add(txtNumeroPlaca);

        jLabel10.setText("Marca:");
        jPanel2.add(jLabel10);
        jPanel2.add(txtMarca);

        jLabel11.setText("Tipo:");
        jPanel2.add(jLabel11);
        jPanel2.add(txtTipo);

        jTabbedPane1.addTab("Informacion vehiculos", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();//cierra la ventana cuando se preciona el boton cancelar
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jComboBoxNumeroPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNumeroPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNumeroPlacaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        
        cond = (Conductor) gestor.consultarConductor(txtNumeroDocumento.getText().toUpperCase(), 1);
        
        if (cond == null){
            Utilidades.mensajeAdvertencia("Usuario no resgitrado", "Atención");
            txtNumeroDocumento.requestFocus();  
            txtNombres.setText("");
            txtApellidos.setText("");
            txtDocumento.setText("");
            txtTipoUsuario.setText("");
            txtMultas.setText("");
            jComboBoxNumeroPlaca.removeAllItems();
            jComboBoxNumeroPlaca2.removeAllItems();
            jComboBoxBahias.removeAllItems();
            txtTipo.setText("");
            txtNumeroPlaca.setText("");
            txtMarca.setText("");
            return;
        }
        
        bahias = new ArrayList();
        bahias =       (ArrayList<Bahia>) gestor.consultarConductor(txtNumeroDocumento.getText().toUpperCase(), 4);

        
        //informacion del ususario
        txtNombres.setText(cond.getNombres());
        txtApellidos.setText(cond.getApellidos());
        txtDocumento.setText(cond.getId());
        txtMultas.setText(""+cond.getMultas());
        txtTipoUsuario.setText(""+cond.getTipo());
        
        //agregar vehiculos al jcombox
        jComboBoxNumeroPlaca.removeAllItems();
        jComboBoxNumeroPlaca2.removeAllItems();
        for(Vehiculo veh: cond.getVehiculos()){
         jComboBoxNumeroPlaca.addItem(veh.getPlaca());  
         jComboBoxNumeroPlaca2.addItem(veh.getPlaca()); 
        }
        
        jComboBoxBahias.removeAllItems();
        if(bahias != null){
            for(int i=0; i<bahias.size(); i++){
                jComboBoxBahias.addItem(""+bahias.get(i).getNumero());   
            }   
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnMostrarInfoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInfoVehiculoActionPerformed
        // TODO add your handling code here:
        //informacion de vehiculos
        for(Vehiculo veh : cond.getVehiculos()) {
            if(jComboBoxNumeroPlaca.getSelectedItem().toString().equals(veh.getPlaca())){
                txtTipo.setText(veh.getTipo().toString());
                txtNumeroPlaca.setText(veh.getPlaca());
                txtMarca.setText(veh.getModelo());
            }
        }
    }//GEN-LAST:event_btnMostrarInfoVehiculoActionPerformed

    private void jComboBoxNumeroPlaca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNumeroPlaca2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNumeroPlaca2ActionPerformed

    private void btnAsignarCupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarCupoActionPerformed
        // TODO add your handling code here:
        if(bahias != null){
            
            for(Vehiculo veh: cond.getVehiculos()){
                if (jComboBoxNumeroPlaca2.getSelectedItem().toString().equals(veh.getPlaca())){
                    for (Bahia bahia : bahias) {
                        if (jComboBoxBahias.getSelectedItem().toString().equals(Integer.toString(bahia.getNumero()))) {
                            JOptionPane.showMessageDialog(null, "Vehiculo con nro de placa: " + veh.getPlaca() + " asigando a la Bahia: " + bahia.getNumero());
                        }
                    }
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "No hay bahias disponibles para " + cond.getTipo());
        }
    }//GEN-LAST:event_btnAsignarCupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIInformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIInformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIInformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIInformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIInformacionUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarCupo;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnMostrarInfoVehiculo;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxBahias;
    private javax.swing.JComboBox jComboBoxNumeroPlaca;
    private javax.swing.JComboBox jComboBoxNumeroPlaca2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelNorte;
    private javax.swing.JPanel jPanelSur;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMultas;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumeroDocumento;
    private javax.swing.JTextField txtNumeroPlaca;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTipoUsuario;
    // End of variables declaration//GEN-END:variables
}
