/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.Usuarios.vista;

import java.awt.Color;

/**
 *
 * @author w
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSur = new javax.swing.JPanel();
        jLabelAdministrativos = new javax.swing.JLabel();
        jLabelDocentes = new javax.swing.JLabel();
        jLabelEstudiantes = new javax.swing.JLabel();
        jLabelVisintantes = new javax.swing.JLabel();
        jLabel01 = new javax.swing.JLabel();
        jLabel02 = new javax.swing.JLabel();
        jLabel03 = new javax.swing.JLabel();
        jLabel04 = new javax.swing.JLabel();
        jPanelCentro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1033, 966));
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanelSur.setBackground(new java.awt.Color(232, 239, 249));
        jPanelSur.setPreferredSize(new java.awt.Dimension(523, 50));
        jPanelSur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAdministrativos.setAlignmentX(0.2F);
        jLabelAdministrativos.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabelAdministrativos.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabelAdministrativos.setName(""); // NOI18N
        jLabelAdministrativos.setPreferredSize(new java.awt.Dimension(4, 2));
        jLabelAdministrativos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelAdministrativosMouseMoved(evt);
            }
        });
        jLabelAdministrativos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAdministrativosMouseClicked(evt);
            }
        });
        jPanelSur.add(jLabelAdministrativos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 18, 18));

        jLabelDocentes.setAlignmentX(0.2F);
        jLabelDocentes.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabelDocentes.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabelDocentes.setName(""); // NOI18N
        jLabelDocentes.setPreferredSize(new java.awt.Dimension(4, 2));
        jPanelSur.add(jLabelDocentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 18, 18));

        jLabelEstudiantes.setAlignmentX(0.2F);
        jLabelEstudiantes.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabelEstudiantes.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabelEstudiantes.setName(""); // NOI18N
        jLabelEstudiantes.setPreferredSize(new java.awt.Dimension(4, 2));
        jPanelSur.add(jLabelEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 18, 18));

        jLabelVisintantes.setAlignmentX(0.2F);
        jLabelVisintantes.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabelVisintantes.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabelVisintantes.setName(""); // NOI18N
        jLabelVisintantes.setPreferredSize(new java.awt.Dimension(4, 2));
        jPanelSur.add(jLabelVisintantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 18, 18));

        jLabel01.setText("Administrativos");
        jPanelSur.add(jLabel01, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel02.setText("Docentes");
        jPanelSur.add(jLabel02, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel03.setText("Estudiantes");
        jPanelSur.add(jLabel03, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel04.setText("Visitantes");
        jPanelSur.add(jLabel04, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        getContentPane().add(jPanelSur, java.awt.BorderLayout.SOUTH);

        jPanelCentro.setBackground(new java.awt.Color(200, 221, 242));
        jPanelCentro.setName(""); // NOI18N
        jPanelCentro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("1");
        jLabel1.setAlignmentX(0.2F);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabel1.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(4, 2));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanelCentro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 18, 18));

        jLabel2.setText("2");
        jLabel2.setAlignmentX(0.2F);
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabel2.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(4, 2));
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jPanelCentro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 18, 18));

        jLabel3.setText("3");
        jLabel3.setAlignmentX(0.2F);
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabel3.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabel3.setName(""); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(4, 2));
        jPanelCentro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 18, 18));

        jLabel4.setText("4");
        jLabel4.setAlignmentX(0.2F);
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabel4.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabel4.setName(""); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(4, 2));
        jPanelCentro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 18, 18));

        jLabel5.setText("5");
        jLabel5.setAlignmentX(0.2F);
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabel5.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabel5.setName(""); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(4, 2));
        jPanelCentro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 18, 18));

        jLabel6.setText("6");
        jLabel6.setAlignmentX(0.2F);
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabel6.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabel6.setName(""); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(4, 2));
        jPanelCentro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 18, 18));

        jLabel7.setText("7");
        jLabel7.setAlignmentX(0.2F);
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabel7.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabel7.setName(""); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(4, 2));
        jPanelCentro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 18, 18));

        jLabel8.setText("8");
        jLabel8.setAlignmentX(0.2F);
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabel8.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabel8.setName(""); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(4, 2));
        jPanelCentro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 18, 18));

        jLabel9.setText("9");
        jLabel9.setAlignmentX(0.2F);
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabel9.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabel9.setName(""); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(4, 2));
        jPanelCentro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 18, 18));

        jLabel10.setText("10");
        jLabel10.setAlignmentX(0.2F);
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabel10.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabel10.setName(""); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(4, 2));
        jPanelCentro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 18, 18));

        jLabel11.setText("11");
        jLabel11.setAlignmentX(0.2F);
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabel11.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabel11.setName(""); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(4, 2));
        jPanelCentro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 18, 18));

        jLabel12.setText("12");
        jLabel12.setAlignmentX(0.2F);
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabel12.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabel12.setName(""); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(4, 2));
        jPanelCentro.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 18, 18));

        jLabel13.setText("13");
        jLabel13.setAlignmentX(0.2F);
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabel13.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabel13.setName(""); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(4, 2));
        jPanelCentro.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 18, 18));

        jLabel14.setText("14");
        jLabel14.setAlignmentX(0.2F);
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabel14.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabel14.setName(""); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(4, 2));
        jPanelCentro.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 18, 18));

        jLabel15.setText("15");
        jLabel15.setAlignmentX(0.2F);
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jLabel15.setMaximumSize(new java.awt.Dimension(10, 2));
        jLabel15.setName(""); // NOI18N
        jLabel15.setPreferredSize(new java.awt.Dimension(4, 2));
        jPanelCentro.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 18, 18));

        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Parqueadero_Img.png"))); // NOI18N
        jPanelCentro.add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 750, 690));

        getContentPane().add(jPanelCentro, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Usuario");

        jMenuItem1.setText("Consultar Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Liberar Cupo");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Vehiculos");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
        //jLabel1.setBackground(Color.WHITE);
        //jLabel1.setOpaque(true);
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        //jLabel1.setBackground(Color.GREEN);
        //jLabel1.setOpaque(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabelAdministrativosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdministrativosMouseMoved
        // TODO add your handling code here:
        //jLabelAdministrativos.setBackground(Color.WHITE);
        //jLabelAdministrativos.setOpaque(true);
    }//GEN-LAST:event_jLabelAdministrativosMouseMoved

    private void jLabelAdministrativosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdministrativosMouseClicked
        // TODO add your handling code here:
        jLabelAdministrativos.setBackground(Color.GREEN);
        jLabelAdministrativos.setOpaque(true);
    }//GEN-LAST:event_jLabelAdministrativosMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        GUIInformacionUsuario consultarUsuario = new GUIInformacionUsuario();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIMenu ins = new GUIMenu();
                ins.setExtendedState(MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel01;
    private javax.swing.JLabel jLabel02;
    private javax.swing.JLabel jLabel03;
    private javax.swing.JLabel jLabel04;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAdministrativos;
    private javax.swing.JLabel jLabelDocentes;
    private javax.swing.JLabel jLabelEstudiantes;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelVisintantes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JPanel jPanelSur;
    // End of variables declaration//GEN-END:variables
}
